#!/bin/sh

start() {
    touch /var/log/aprenderer.log
    ln -s -f /var/log/aprenderer.log /usr/aprenderer/aprenderer.log
    printf "Starting APlayer UPNP: "
    /usr/aprenderer/upnp/squeeze2upnp -z -k -I > /dev/null 2>&1
    cd /usr/aprenderer; ./aprenderer > /dev/null 2>&1 && echo "OK" || echo "FAIL"
    renice -15 `pidof aprenderer`
    sync
    MIXER=`amixer 2>/dev/null| awk -F "'" 'NR==1 {print $2; exit}'`
    /usr/bin/amixer set "$MIXER" unmute
    }
stop() {
    MIXER=`amixer 2>/dev/null| awk -F "'" 'NR==1 {print $2; exit}'`
    /usr/bin/amixer set "$MIXER" mute
    killall -9 aprenderer squeeze2upnp
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
