#!/bin/sh

start() {
    touch /var/log/apscream.log
    ln -s -f /var/log/apscream.log /usr/apscream/apscream.log
    printf "Starting APscream: "
    cd /usr/apscream; nice -n -30 ./apscream > /dev/null 2>&1 && echo "OK" || echo "FAIL"
    sync
    MIXER=`amixer 2>/dev/null| awk -F "'" 'NR==1 {print $2; exit}'`
    /usr/bin/amixer set "$MIXER" unmute
    }
stop() {
    MIXER=`amixer 2>/dev/null| awk -F "'" 'NR==1 {print $2; exit}'`
    /usr/bin/amixer set "$MIXER" mute
    killall -9 apscream
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
