#!/bin/sh

start() {
    touch /var/log/apscream.log
    ln -s -f /var/log/apscream.log /usr/apscream/apscream.log
    printf "Starting APscream: "
    cd /usr/apscream; ./apscream > /dev/null 2>&1 && echo "OK" || echo "FAIL"
    sleep 0.5
    pid=$(pidof apscream)
    if [ -n "$pid" ]; then
    renice -15 $pid
    for tid in $(ls /proc/$pid/task/); do
        renice -15 $tid
    done
    fi
    sync
    MIXER=`amixer 2>/dev/null| awk -F "'" 'NR==1 {print $2; exit}'`
    /usr/bin/amixer set "$MIXER" unmute
    }
stop() {
    MIXER=`amixer 2>/dev/null| awk -F "'" 'NR==1 {print $2; exit}'`
    /usr/bin/amixer set "$MIXER" mute
    killall -9 apscream
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
