#!/bin/sh


start() {
    touch /var/log/aplayer.log
    ln -s -f /var/log/aplayer.log /usr/aprenderer/aplayer.log
    printf "Starting APlayer: "
    cd /usr/aplayer; nice -n -30 ./aplayer > /dev/null 2>&1 && echo "OK" || echo "FAIL"
    sleep 0.5
    if [ -f /tmp/mixer_control_cache ]; then
        MIXER=$(cat /tmp/mixer_control_cache | cut -d, -f1 | tr -d "'")
        [ -n "$MIXER" ] && amixer set "$MIXER" unmute 2>/dev/null
    fi
    sync
    }
stop() {
    killall -9 aplayer
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
