#!/bin/sh

start() {
    touch /var/log/aplayer.log
    ln -s -f /var/log/aplayer.log /usr/aprenderer/aplayer.log
    printf "Starting APlayer: "
    cd /usr/aplayer; ./aplayer > /dev/null 2>&1 && echo "OK" || echo "FAIL"
    renice -15 `pidof aplayer`
    sync
    }
stop() {
    killall -9 aplayer
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
