#!/bin/sh

start() {
    printf "Starting mpd: "
    sync
    ln -s /etc/rc.pure/S95upmpdcli /etc/init.d/S95upmpdcli
    /etc/init.d/S95upmpdcli start
    /usr/bin/mpd
    renice -15 `pidof mpd`
    }
stop() {
    killall -9 mpd
    killall -9 upmpdcli
    rm -f /etc/init.d/S95upmpdcli
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
