#!/bin/sh

start() {
    printf "Starting NAA: "
    /usr/sbin/networkaudiod > /dev/null 2>&1 &
    sleep 0.5
    if [ -f /tmp/mixer_control_cache ]; then
        MIXER=$(cat /tmp/mixer_control_cache | cut -d, -f1 | tr -d "'")
        [ -n "$MIXER" ] && amixer set "$MIXER" unmute 2>/dev/null
    fi
    }
stop() {
    killall -9 networkaudiod
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
