#!/bin/sh

start() {
    printf "Starting RoonBrige: "
    MAC=`cat /sys/class/net/eth0/address | tr 'a-z' 'A-Z'`
    sed -i "s/^.*\"unique_id\".*/    \"unique_id\": \"$MAC\" ,/" /etc/raat.conf
    /opt/RoonReady/raat_app /etc/raat.conf > /dev/null 2>&1 &
    sleep 0.5
    pid=$(pidof raat_app)
    if [ -n "$pid" ]; then
    renice -15 $pid
    for tid in $(ls /proc/$pid/task/); do
        renice -15 $tid
    done
    fi

    MIXER=`amixer 2>/dev/null| awk -F "'" 'NR==1 {print $2; exit}'`
    /usr/bin/amixer set "$MIXER" unmute
    }
stop() {
    MIXER=`amixer 2>/dev/null| awk -F "'" 'NR==1 {print $2; exit}'`
    /usr/bin/amixer set "$MIXER" mute
    killall -9 raat_app
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
