#!/bin/sh


start() {
    printf "Starting RoonBrige: "
    MAC=`cat /sys/class/net/eth0/address | tr 'a-z' 'A-Z'`
    sed -i "s/^.*\"unique_id\".*/    \"unique_id\": \"$MAC\" ,/" /etc/raat.conf
    renice -15 $$ 
    /opt/RoonReady/raat_app /etc/raat.conf > /dev/null 2>&1 &
    sleep 0.5
    if [ -f /tmp/mixer_control_cache ]; then
        MIXER=$(cat /tmp/mixer_control_cache | cut -d, -f1 | tr -d "'")
        [ -n "$MIXER" ] && amixer set "$MIXER" unmute 2>/dev/null
    fi
    }
stop() {
    killall -9 raat_app
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
