#!/bin/sh

MIXER=`sed 's/,.*//' /tmp/mixer_control_cache`

start() {
    printf "Starting RoonBrige: "
    MAC=`cat /sys/class/net/eth0/address | tr 'a-z' 'A-Z'`
    sed -i "s/^.*\"unique_id\".*/    \"unique_id\": \"$MAC\" ,/" /etc/raat.conf
    /opt/RoonReady/raat_app /etc/raat.conf > /dev/null 2>&1 &
    sleep 0.1
    pid=$(pidof raat_app)
    if [ -n "$pid" ]; then
    renice -15 $pid
    for tid in $(ls /proc/$pid/task/); do
        renice -15 $tid
    done
    fi

    [ -n "$MIXER" ] && /usr/bin/amixer set "$MIXER" unmute 2>/dev/null
    }
stop() {
    [ -n "$MIXER" ] && /usr/bin/amixer set "$MIXER" mute 2>/dev/null
    killall -9 raat_app
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
