#!/bin/sh

MIXER=`sed 's/,.*//' /tmp/mixer_control_cache`


start() {
	printf "Starting shairport-sync: "
	/usr/bin/shairport-sync -d
	sleep 0.1
        pid=$(pidof shairport-sync)
        if [ -n "$pid" ]; then
        renice -15 $pid
        for tid in $(ls /proc/$pid/task/); do
            sleep 0.1
            renice -15 $tid
        done
        fi
	[ -n "$MIXER" ] && /usr/bin/amixer set "$MIXER" unmute 2>/dev/null
    }
stop() {
    [ -n "$MIXER" ] && /usr/bin/amixer set "$MIXER" mute 2>/dev/null
    killall -9 shairport-sync
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
