#!/bin/sh

start() {
	printf "Starting shairport-sync: "
	/usr/bin/shairport-sync -d
	sleep 0.5
        pid=$(pidof shairport-sync)
        if [ -n "$pid" ]; then
        renice -15 $pid
        for tid in $(ls /proc/$pid/task/); do
            renice -15 $tid
        done
        fi
	MIXER=`amixer 2>/dev/null| awk -F "'" 'NR==1 {print $2; exit}'`
	/usr/bin/amixer set "$MIXER" unmute
    }
stop() {
    MIXER=`amixer 2>/dev/null| awk -F "'" 'NR==1 {print $2; exit}'`
    /usr/bin/amixer set "$MIXER" mute
    killall -9 shairport-sync
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
