#!/bin/sh

start() {
	printf "Starting shairport-sync: "
	/usr/bin/shairport-sync -d
	renice -15 `pidof shairport-sync`
        MIXER=`amixer 2>/dev/null| awk -F "'" 'NR==1 {print $2; exit}'`
	/usr/bin/amixer set "$MIXER" unmute
    }
stop() {
    MIXER=`amixer 2>/dev/null| awk -F "'" 'NR==1 {print $2; exit}'`
    /usr/bin/amixer set "$MIXER" mute
    killall -9 shairport-sync
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
