#!/bin/sh

start() {
    /etc/init.d/S48sntp start
    printf "Starting Spotify: "
    NAME=`hostname`_`ifconfig eth0 | awk '/inet addr/{print substr($2,6)}'`
    /usr/bin/librespot --dither none --disable-audio-cache --bitrate 320 --initial-volume 100 --name $NAME > /dev/null 2>&1 &
    renice -15 `pidof librespot`
    }
stop() {
    killall -9 librespot
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


