#!/bin/sh

start() {
    printf "Starting APScream: "
    /usr/apscream/apscream  > /dev/null 2>&1 &
    renice -15 `pidof apscream`
    }
stop() {
    killall -9 apscream
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
