#!/bin/sh

start() {
    printf "Starting Tidal Connect: "
    export LD_LIBRARY_PATH=/usr/lib/tidal:$LD_LIBRARY_PATH
    tidalconnect -f LuckFox --tc-certificate-path "/etc/ssl/private/IfiAudio_ZenStream.dat" --codec-mpegh true --disable-app-security false --disable-web-security false --codec-mqa true --enable-mqa-passthrough true &
    sleep 0.5
    renice -15 `pidof tidalconnect`
}
    
stop() {
    	killall -9 tidalconnect
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
