#!/bin/sh

start() {
    printf "Starting Tidalconnect: "
    export LD_LIBRARY_PATH=/usr/lib/tidal
    (
    tidalconnect \
    --netif-for-deviceid eth0 \
    -f LuckFox \
    --codec-mpegh false \
    --codec-mqa false \
    --model-name "OEM" \
    --disable-app-security false \
    --disable-web-security true \
    --enable-mqa-passthrough true \
    --log-level 3 \
    --tc-certificate-path "/etc/ssl/private/tcon.crt" \
    --clientid "VCjoaRrbaMU005Tk" \
    > /dev/null 2>&1 < /dev/null &
    ) &
    sleep 1
    renice -10 `pidof tidalconnect` 2>/dev/null
    MIXER=`amixer 2>/dev/null| awk -F "'" 'NR==1 {print $2; exit}'`
    /usr/bin/amixer set "$MIXER" unmute
    exit
    }
stop() {
	MIXER=`amixer 2>/dev/null| awk -F "'" 'NR==1 {print $2; exit}'`
	/usr/bin/amixer set "$MIXER" mute
	killall -9 tidalconnect
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
