#!/bin/sh

if [ -f /etc/usb_to_i2s.state ]; then
	# USBtoI2S mode enabled - load gadget modules
	insmod /lib/modules/dwc3_gadget.ko
	modprobe dwc3-of-simple
else
	# USBtoI2S mode disabled - load host modules
	modprobe dwc3
	modprobe dwc3-of-simple
fi

exit 0
