#!/bin/sh
### BEGIN INIT INFO
# Provides:          dtbocfg
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Load dtbocfg kernel module
### END INIT INFO

MODULE_PATH="/lib/modules/5.10.160/extra/dtbocfg.ko"
MODULE_NAME="dtbocfg"

case "$1" in
    start)
        echo "Loading module $MODULE_NAME"
        if ! lsmod | grep -q "^${MODULE_NAME}"; then
            insmod "$MODULE_PATH"
            echo "Module $MODULE_NAME loaded"
	else
            echo "Module $MODULE_NAME already loaded"
        fi
        ;;
    stop)
        echo "Unloading module $MODULE_NAME"
        if lsmod | grep -q "^${MODULE_NAME}"; then
            rmmod "$MODULE_NAME"
            echo "Module $MODULE_NAME unloaded"
        else
            echo "Module $MODULE_NAME not loaded"
        fi
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    status)
        if lsmod | grep -q "^${MODULE_NAME}"; then
            echo "Module $MODULE_NAME is loaded"
        else
            echo "Module $MODULE_NAME is not loaded"
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit 0
