#!/bin/sh
#
# Run the mdev daemon
#

DAEMON="mdev"
PIDFILE="/var/run/$DAEMON.pid"

start() {
	echo -n "Starting $DAEMON... "
	
	# Set mdev as hotplug helper
	echo "/sbin/mdev" > /proc/sys/kernel/hotplug
	
	# Start mdev daemon for monitoring
	start-stop-daemon -S -b -m -p $PIDFILE -x /sbin/mdev -- -df
	[ $? -eq 0 ] && echo "OK" || echo "ERROR"

	# Coldplug existing devices
	/sbin/mdev -s
}

stop() {
	echo -n "Stopping $DAEMON... "
	start-stop-daemon -K -p $PIDFILE
	[ $? -eq 0 ] && echo "OK" || echo "ERROR"
	
	# Clear hotplug helper
	echo "" > /proc/sys/kernel/hotplug
}

restart() {
	stop
	start
}

case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?