#!/bin/sh

source /etc/i2s.conf

start() {

	if [ "$MODE" == "pll" ]; then
	    exit 0
	fi

	if [ "$MCLK" == "512" ]; then   
    	    insmod /lib/modules/5.10.160/extra/dtbocfg.ko
    	    sleep 0.5
    	    mkdir -p /sys/kernel/config/device-tree/overlays/512
    	    cat /etc/overlays/512.dtbo > /sys/kernel/config/device-tree/overlays/512/dtbo
    	    echo 1 > /sys/kernel/config/device-tree/overlays/512/status
    	fi
}
stop() {

	[ -f "/sys/kernel/config/device-tree/overlays/512/status" ] && echo 0 > /sys/kernel/config/device-tree/overlays/512/status

}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
